apiVersion: v1
kind: Pod
metadata:
  labels:
    app: music
    service: music
  name: hue-music
spec:
  containers:
    - name: hue-music
      image: busybox
      livenessProbe:
        httpGet:
          path: /pulse
          port: 8888
          httpHeaders:
          - name: X-Custom-Header
            value: ItsAlive
        initialDelaySeconds: 30
        timeoutSeconds: 1
