kind: Pod
apiVersion: v1
metadata:
  name: the-pod
spec:
  containers:
  - name: the-container
    image: g1g1/py-kube:0.2
    command: ["bash"]
    args: ["-c", "echo started...; while true ; do sleep 1 ; done"]
    volumeMounts:
    - mountPath: "/mnt/data"
      name: persistent-volume
  volumes:
  - name: persistent-volume
    persistentVolumeClaim:
      claimName: local-storage-claim