apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: staging
commonLabels:
  environment: staging
bases:
- ../../base

patchesStrategicMerge:
  - hue-learn-patch.yaml

resources:
- namespace.yaml